# Site settings
title: Ruby Zero
email: xuanvinh@live.com
description: > # this means to ignore newlines until "baseurl:"
  Ruby on Rails, programming and other random thing
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://zinh.github.io" # the base hostname & protocol for your site
github_username:  zinh

# Build settings
markdown: kramdown
gems:
  - jekyll-sitemap
